version: '3'
services:
  chat-assistant:
    image: caoshiliang/chat-assistant:latest
    environment:
      - spring.redis.host=redis
      - spring.redis.port=6379
      - openai.api-key=YOUR_OPEN_AI_API_KEY
      - slack.app-token=YOUR_SLACK_APP_TOKEN
      - slack.bot-oauth-token=YOUR_SLACK_BOT_OAUTH_TOKEN
    ports:
      - "10001:10001"
    depends_on:
      - redis
  redis:
    image: redis:latest
